// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSIrbCbqSmpm3fiaARRzGV6Vv6xXWCtM',
    appId: '1:428200440634:web:ddc2b1ae692646fc3f9603',
    messagingSenderId: '428200440634',
    projectId: 'mealmate-4474c',
    authDomain: 'mealmate-4474c.firebaseapp.com',
    storageBucket: 'mealmate-4474c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0pQjIfw6lFr_nLGkd20x1wGl0_9GJpIE',
    appId: '1:428200440634:android:04d48188b3e680503f9603',
    messagingSenderId: '428200440634',
    projectId: 'mealmate-4474c',
    storageBucket: 'mealmate-4474c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvu5HeQuzzZtymEZpDznf6Vtm9bZGlGL0',
    appId: '1:428200440634:ios:f0838d9d8a35806b3f9603',
    messagingSenderId: '428200440634',
    projectId: 'mealmate-4474c',
    storageBucket: 'mealmate-4474c.appspot.com',
    iosBundleId: 'com.example.mealmate',
  );
}
